package com.example.ecommerceapp.navigation

object Routes {
    val admin="Admin"
    val login = "LogIn"
    val singIn = "SingIn"
    val allCategories = "AllCategories"
    val shirt = "Shirt"
    val pant = "Pant"
    val panjabi = "Panjabi"
    val t_shirt = "T-Shirt"
    val polo = "Polo"
    val salwarKameez = "SalwarKameez"
    val kameez = "Kameez"
    val saree = "Saree"
    val camera = "Camera"
    val earbuds = "Earbuds"
    val smartWatch = "SmartWatch"
    val tv = "Tv"
    val headphone = "Headphone"
    val keyboard = "Keyboard"
    val mouse = "Mouse"
    val speaker = "Speaker"
    val cart = "Cart"
    val newcode = "TRY"
    val search = "Search"
    val home = "Home"
    val profile="Profile"
}
